-- Temporary JSON embedding fallback.
--
-- The staging PostgreSQL server does not have the pgvector extension installed.
-- Embeddings remain stored in the existing JSON columns and cosine similarity is
-- calculated by the backend. Keep this migration as a no-op so fresh databases
-- retain the same migration history while pgvector is deferred.
